"""empty message

Revision ID: 426ba29e30f8
Revises: 
Create Date: 2018-05-23 13:18:34.483258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '426ba29e30f8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repository',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repository', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=240), nullable=True),
    sa.Column('in_scope', sa.String(length=3), nullable=True),
    sa.Column('bp', sa.String(length=20), nullable=True),
    sa.Column('employee', sa.String(length=64), nullable=True),
    sa.Column('m_8', sa.String(length=4), nullable=True),
    sa.Column('m_9', sa.String(length=4), nullable=True),
    sa.Column('m_10', sa.String(length=4), nullable=True),
    sa.Column('m_11', sa.String(length=4), nullable=True),
    sa.Column('readme', sa.String(length=10000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repository_bp'), 'repository', ['bp'], unique=False)
    op.create_index(op.f('ix_repository_description'), 'repository', ['description'], unique=False)
    op.create_index(op.f('ix_repository_employee'), 'repository', ['employee'], unique=False)
    op.create_index(op.f('ix_repository_in_scope'), 'repository', ['in_scope'], unique=False)
    op.create_index(op.f('ix_repository_repository'), 'repository', ['repository'], unique=False)
    op.create_table('module',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('addon', sa.String(length=240), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=True),
    sa.Column('summary', sa.String(length=240), nullable=True),
    sa.Column('version_8', sa.String(length=10), nullable=True),
    sa.Column('version_9', sa.String(length=10), nullable=True),
    sa.Column('version_10', sa.String(length=10), nullable=True),
    sa.Column('version_11', sa.String(length=10), nullable=True),
    sa.Column('installable_8', sa.String(length=10), nullable=True),
    sa.Column('installable_9', sa.String(length=10), nullable=True),
    sa.Column('installable_10', sa.String(length=10), nullable=True),
    sa.Column('installable_11', sa.String(length=10), nullable=True),
    sa.Column('readme_8', sa.String(length=20), nullable=True),
    sa.Column('readme_9', sa.String(length=20), nullable=True),
    sa.Column('readme_10', sa.String(length=20), nullable=True),
    sa.Column('readme_11', sa.String(length=20), nullable=True),
    sa.Column('readme_text_8', sa.String(length=10000), nullable=True),
    sa.Column('readme_text_9', sa.String(length=10000), nullable=True),
    sa.Column('readme_text_10', sa.String(length=10000), nullable=True),
    sa.Column('readme_text_11', sa.String(length=10000), nullable=True),
    sa.Column('rating_8', sa.String(length=50), nullable=True),
    sa.Column('rating_9', sa.String(length=50), nullable=True),
    sa.Column('rating_10', sa.String(length=50), nullable=True),
    sa.Column('rating_11', sa.String(length=50), nullable=True),
    sa.Column('review_8', sa.String(length=10000), nullable=True),
    sa.Column('review_9', sa.String(length=10000), nullable=True),
    sa.Column('review_10', sa.String(length=10000), nullable=True),
    sa.Column('review_11', sa.String(length=10000), nullable=True),
    sa.Column('repo_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['repo_name'], ['repository.repository'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_module_addon'), 'module', ['addon'], unique=False)
    op.create_index(op.f('ix_module_installable_10'), 'module', ['installable_10'], unique=False)
    op.create_index(op.f('ix_module_installable_11'), 'module', ['installable_11'], unique=False)
    op.create_index(op.f('ix_module_installable_8'), 'module', ['installable_8'], unique=False)
    op.create_index(op.f('ix_module_installable_9'), 'module', ['installable_9'], unique=False)
    op.create_index(op.f('ix_module_rating_10'), 'module', ['rating_10'], unique=False)
    op.create_index(op.f('ix_module_rating_11'), 'module', ['rating_11'], unique=False)
    op.create_index(op.f('ix_module_rating_8'), 'module', ['rating_8'], unique=False)
    op.create_index(op.f('ix_module_rating_9'), 'module', ['rating_9'], unique=False)
    op.create_index(op.f('ix_module_readme_10'), 'module', ['readme_10'], unique=False)
    op.create_index(op.f('ix_module_readme_11'), 'module', ['readme_11'], unique=False)
    op.create_index(op.f('ix_module_readme_8'), 'module', ['readme_8'], unique=False)
    op.create_index(op.f('ix_module_readme_9'), 'module', ['readme_9'], unique=False)
    op.create_index(op.f('ix_module_summary'), 'module', ['summary'], unique=False)
    op.create_index(op.f('ix_module_version_10'), 'module', ['version_10'], unique=False)
    op.create_index(op.f('ix_module_version_11'), 'module', ['version_11'], unique=False)
    op.create_index(op.f('ix_module_version_8'), 'module', ['version_8'], unique=False)
    op.create_index(op.f('ix_module_version_9'), 'module', ['version_9'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_module_version_9'), table_name='module')
    op.drop_index(op.f('ix_module_version_8'), table_name='module')
    op.drop_index(op.f('ix_module_version_11'), table_name='module')
    op.drop_index(op.f('ix_module_version_10'), table_name='module')
    op.drop_index(op.f('ix_module_summary'), table_name='module')
    op.drop_index(op.f('ix_module_readme_9'), table_name='module')
    op.drop_index(op.f('ix_module_readme_8'), table_name='module')
    op.drop_index(op.f('ix_module_readme_11'), table_name='module')
    op.drop_index(op.f('ix_module_readme_10'), table_name='module')
    op.drop_index(op.f('ix_module_rating_9'), table_name='module')
    op.drop_index(op.f('ix_module_rating_8'), table_name='module')
    op.drop_index(op.f('ix_module_rating_11'), table_name='module')
    op.drop_index(op.f('ix_module_rating_10'), table_name='module')
    op.drop_index(op.f('ix_module_installable_9'), table_name='module')
    op.drop_index(op.f('ix_module_installable_8'), table_name='module')
    op.drop_index(op.f('ix_module_installable_11'), table_name='module')
    op.drop_index(op.f('ix_module_installable_10'), table_name='module')
    op.drop_index(op.f('ix_module_addon'), table_name='module')
    op.drop_table('module')
    op.drop_index(op.f('ix_repository_repository'), table_name='repository')
    op.drop_index(op.f('ix_repository_in_scope'), table_name='repository')
    op.drop_index(op.f('ix_repository_employee'), table_name='repository')
    op.drop_index(op.f('ix_repository_description'), table_name='repository')
    op.drop_index(op.f('ix_repository_bp'), table_name='repository')
    op.drop_table('repository')
    # ### end Alembic commands ###
