"""empty message

Revision ID: f6819d70e7d3
Revises: 426ba29e30f8
Create Date: 2018-05-28 10:04:51.334025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6819d70e7d3'
down_revision = '426ba29e30f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('module', sa.Column('customer_10', sa.String(length=50), nullable=True))
    op.add_column('module', sa.Column('customer_11', sa.String(length=50), nullable=True))
    op.add_column('module', sa.Column('customer_8', sa.String(length=50), nullable=True))
    op.add_column('module', sa.Column('customer_9', sa.String(length=50), nullable=True))
    op.add_column('module', sa.Column('vertical_10', sa.String(length=50), nullable=True))
    op.add_column('module', sa.Column('vertical_11', sa.String(length=50), nullable=True))
    op.add_column('module', sa.Column('vertical_8', sa.String(length=50), nullable=True))
    op.add_column('module', sa.Column('vertical_9', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_module_customer_10'), 'module', ['customer_10'], unique=False)
    op.create_index(op.f('ix_module_customer_11'), 'module', ['customer_11'], unique=False)
    op.create_index(op.f('ix_module_customer_8'), 'module', ['customer_8'], unique=False)
    op.create_index(op.f('ix_module_customer_9'), 'module', ['customer_9'], unique=False)
    op.create_index(op.f('ix_module_vertical_10'), 'module', ['vertical_10'], unique=False)
    op.create_index(op.f('ix_module_vertical_11'), 'module', ['vertical_11'], unique=False)
    op.create_index(op.f('ix_module_vertical_8'), 'module', ['vertical_8'], unique=False)
    op.create_index(op.f('ix_module_vertical_9'), 'module', ['vertical_9'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_module_vertical_9'), table_name='module')
    op.drop_index(op.f('ix_module_vertical_8'), table_name='module')
    op.drop_index(op.f('ix_module_vertical_11'), table_name='module')
    op.drop_index(op.f('ix_module_vertical_10'), table_name='module')
    op.drop_index(op.f('ix_module_customer_9'), table_name='module')
    op.drop_index(op.f('ix_module_customer_8'), table_name='module')
    op.drop_index(op.f('ix_module_customer_11'), table_name='module')
    op.drop_index(op.f('ix_module_customer_10'), table_name='module')
    op.drop_column('module', 'vertical_9')
    op.drop_column('module', 'vertical_8')
    op.drop_column('module', 'vertical_11')
    op.drop_column('module', 'vertical_10')
    op.drop_column('module', 'customer_9')
    op.drop_column('module', 'customer_8')
    op.drop_column('module', 'customer_11')
    op.drop_column('module', 'customer_10')
    # ### end Alembic commands ###
